### ISSUE TITLE
Disable @typescript-eslint/unbound-method in test files

### ISSUE THREAD

**Issue by uPaymeiFixit** [dudeofawesome/code-style#74]
Add this

```yaml
overrides:
  - files:
      - '**/test/**'
      - '**/__test__/**'
      - '*.test.*'
      - '*.spec.*'
      - '*.unit.*'
      - '*.e2e.*'
    rules:
      '@typescript-eslint/unbound-method': 'off'
```

to https://github.com/dudeofawesome/code-style/blob/main/packages/eslint-config-jest/src/base.ts
